sudo: required

language: python

python:
  - "2.7"
  - "3.4"

services:
  - docker

env:
  - OAR_VERSION=2.5.7

install:
  - pip install .

script:
  - oardocker init -e jessie
  - oardocker build
  - oardocker install http://oar-ftp.imag.fr/oar/2.5/sources/stable/oar-$OAR_VERSION.tar.gz
  - oardocker start -n 2
  - oardocker exec server cat /oar_version | grep $OAR_VERSION
  - oardocker status | grep server | grep Up
  - oardocker status | grep node1 | grep Up
  - oardocker status | grep node2 | grep Up
  - oardocker status | grep frontend | grep Up
  - oardocker status | grep rsyslog | grep Up
